[package]
name = "atium"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dyn-clone = "1.0.16"
image = "0.24.8"
nom = "7.1.3"
tempfile = "3.9.0"
