name: Rust Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test --verbose

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true
      - name: Check formatting
        run: cargo fmt -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - name: Lint with Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  generate-and-deploy-docs:
    name: Generate and Deploy Docs
    runs-on: ubuntu-latest
    needs: [test, fmt, clippy, coverage] # Ensure this job runs after the others
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures history is available for GH Pages deployment
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rust-docs
          override: true
      - name: Generate Documentation
        run: cargo doc --no-deps
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.1
        with:
          branch: gh-pages  # The branch the action should deploy to.
          folder: target/doc  # The folder the action should deploy.
